---
backupLocation: /var/lib/rouge
hosts:
    -   hostname: athena
        username: tianon
        include:
            - /home/tianon
            - /etc
        exclude:
# files in /etc/init.d are provided by installing software
            - /etc/init.d
        exempt:
            - /etc/init.d/my_custom_init_script
        rsyncExtra: '--compress'
    -   hostname: susan
        username: tianon
        privkey: /home/tianon/.ssh/alternate_id_dsa
        include:
            - /home/tianon
            - /etc/bind
            - /var/bind/{pri,sec}
            - /etc/dhcp
            - /etc/shorewall
            - /etc/shorewall6
            - /etc/unrealircd
            - /etc/squid
            - /etc/postfix
            - /etc/ntp.conf
            - /etc/make.conf
            - /etc/exports
            - /etc/cups
            - /etc/cron*
            - /etc/apache2
